const recognitionColumns = [
  "filename",
  "product_name",
  "price_default",
  "price_card",
  "price_discount",
  "barcode",
  "discount_amount",
  "id_sku",
  "print_datetime",
  "code",
  "additional_info",
  "color",
  "special_symbols",
  "frame_timestamp",
  "x_min",
  "y_min",
  "x_max",
  "y_max",
  "qr_code_barcode",
  "price1_qr",
  "price2_qr",
  "price3_qr",
  "price4_qr",
  "wholesale_level_1_count",
  "wholesale_level_1_price",
  "wholesale_level_2_count",
  "wholesale_level_2_price",
  "action_price_qr",
  "action_code_qr",
];

export default recognitionColumns;
